# Generated by Django 4.2.7 on 2023-11-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_word', models.CharField(max_length=200, unique=True)),
                ('output1', models.CharField(max_length=100)),
                ('output2', models.CharField(max_length=100)),
                ('output3', models.CharField(max_length=100)),
                ('output4', models.CharField(max_length=100)),
                ('output5', models.CharField(max_length=100)),
                ('output6', models.CharField(max_length=100)),
                ('output7', models.CharField(max_length=100)),
                ('output8', models.CharField(max_length=100)),
                ('output9', models.CharField(max_length=100)),
                ('output10', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronounciation', models.CharField(max_length=100)),
                ('definition', models.TextField()),
            ],
        ),
    ]
