# Generated by Django 4.2.7 on 2023-11-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='output_word',
            field=models.TextField(),
        ),
    ]
